name: decision-transformer-gym
channels:
- pytorch
dependencies:
- python=3.11
- anaconda
#- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.25
  - mujoco-py==2.1.2.14
  - numpy<2
  - torch>=2.2
  - transformers>=4.5.1
  - wandb>=0.9.1
